name: vazifa20
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.7.0
  google_places_autocomplete_text_field: ^0.1.3
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
